### ISSUE TITLE
Keine Calls kommen an

### ISSUE THREAD

**Issue by philippkayser** [qmexnetworks/3cx-zammad-bridge#1]
Bei uns funktioniert es leider nicht.

```
config.yaml
Bridge:
  poll_interval: 0.5

3CX:
  user: admin
  pass:
  host: https://****.3cx.eu
  group: Gruppenname
  extension_digits: 2
  trunk_digits: 12
  queue_extension: 80

Zammad:
  endpoint: https://zammad.*****.net/api/v1/cti/sw****
  log_missed_queue_calls: true
```

/usr/local/bin/zammadbridge
2021/04/20 11:02:46 Loaded extensions: [00 10 13 51 52]

keine weiteren Einträge

```
zammad-scheduler_1      | I, [2021-04-20T11:04:39.015080 #1-47457575594460]  INFO -- : execute Channel.fetch (try_count 0)...
zammad-scheduler_1      | I, [2021-04-20T11:04:39.017138 #1-47457575594460]  INFO -- : ended Channel.fetch took: 0.018983219 seconds.
zammad-railsserver_1    | I, [2021-04-20T11:04:46.792119 #1-47126010389840]  INFO -- : Started GET "/api/v1/http_logs/cti?limit=50&_=1618916604073" for 172.18.0.2 at 2021-04-20 11:04:46 +0000
zammad-railsserver_1    | I, [2021-04-20T11:04:46.802377 #1-47126010389840]  INFO -- : Processing by HttpLogsController#index as JSON
zammad-railsserver_1    | I, [2021-04-20T11:04:46.802573 #1-47126010389840]  INFO -- :   Parameters: {"limit"=>"50", "_"=>"1618916604073", "facility"=>"cti"}
zammad-railsserver_1    | I, [2021-04-20T11:04:46.829943 #1-47126010389840]  INFO -- : Completed 200 OK in 27ms (Views: 6.7ms | ActiveRecord: 6.5ms)
zammad-nginx_1          | 172.18.0.2 - - [20/Apr/2021:11:04:46 +0000] "GET /api/v1/http_logs/cti?limit=50&_=1618916604073 HTTP/1.1" 200 1236 "https://zammad.*******.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
```
