### ISSUE TITLE
v0.7.0-beta1 not getting the call

### ISSUE THREAD

**Issue by macoune** [qmexnetworks/3cx-zammad-bridge#10]
Hi,
First of all, thank you and well done for this nice connector!
I'm trying to get it working with our 3CX v20 ENT edition (I were happily using it on v18).

On 3CX side:
3CX Version 20.0 Update 4 (Build 487 Release)
2 digits extensions, 2 call queues(80,82), 6 agents (19,22,23,24,25,26) all in the same department
API integration set with Call Control API granted and all concerned extensions

Here is the /etc/3cx-zammad-bridge/config.yaml config

```
Bridge:
  poll_interval: 0.5 # decimal; The number of seconds to wait in between polling 3CX for calls

3CX:
    #user: "66"
    #pass: "xxxx"
    # For versions v20 and above, define these two:
    client_id: "zammadbridge"
    client_secret: "xxxxxxxxxxxx"
    host: "https://xxxxxxxxx.3cx.fr"
    group: "xxxxxxxx"
    extension_digits: 2 # numeric; How many digits the internal extensions have 
    trunk_digits: 5 # numeric; How many digits the numbers in the trunk have
#    queue_extension: 82 # numeric; The number of the queue that the bridge should also listen to
    country_prefix: 33 # numeric; optional; The country dialing prefix to remove from the numbers

Zammad:
    endpoint: https://xxxxxxxxxxxx.xxx/api/v1/cti/xxxxxxxxxxxxxxxx # The URL of your Zammad server, including the secret in the URL
    log_missed_queue_calls: true # boolean; Whether or not you want to log missed calls to your queue

```

When a call arrive, I can see it on /var/log/3cx-zammad-bridge.err.log:
`{"level":"info","response":[{"dn":"zammadbridge","participants":[]},{"dn":"19","participants":[]},{"dn":"23","participants":[]},{"dn":"24","participants":[]},{"dn":"22","participants":[]},{"dn":"25","participants":[]},{"dn":"26","participants":[]},{"dn":"27","participants":[]}],"time":1739309113,"message":"Received call control response"}
...
{"level":"info","response":[{"dn":"zammadbridge","participants":[]},{"dn":"19","participants":[{"id":8213,"status":"Ringing","dn":"19","party_caller_name":"+33XXXXXXXXX","party_dn":"10000","party_caller_id":"+33XXXXXXXXX","party_did":"","callid":588}]},{"dn":"23","participants":[]},{"dn":"24","participants":[]},{"dn":"22","participants":[]},{"dn":"25","participants":[]},{"dn":"26","participants":[]},{"dn":"27","participants":[]}],"time":1739309114,"message":"Received call control response"}
{"level":"trace","call_id":"588","direction":"","from":"","to":"","time":1739309114,"message":"Call is not relevant"}
...
{"level":"info","response":[{"dn":"zammadbridge","participants":[]},{"dn":"19","participants":[{"id":8213,"status":"Connected","dn":"19","party_caller_name":"+33XXXXXXXXX","party_dn":"10000","party_caller_id":"+33XXXXXXXXX","party_did":"","callid":588}]},{"dn":"23","participants":[]},{"dn":"24","participants":[]},{"dn":"22","participants":[]},{"dn":"25","participants":[]},{"dn":"26","participants":[]},{"dn":"27","participants":[]}],"time":1739309119,"message":"Received call control response"}
{"level":"trace","call_id":"588","direction":"","from":"","to":"","time":1739309119,"message":"Call is not relevant"}
...
{"level":"info","response":[{"dn":"zammadbridge","participants":[]},{"dn":"19","participants":[]},{"dn":"23","participants":[]},{"dn":"24","participants":[]},{"dn":"22","participants":[]},{"dn":"25","participants":[]},{"dn":"26","participants":[]},{"dn":"27","participants":[]}],"time":1739309134,"message":"Received call control response"}
`

But the call is not sent to Zammad ("Call is not relevant"), nothing on /var/log/3cx-zammad-bridge.out.log.

Do you know if that's something I doing wrong?

Thank you
